background {
    monitor =
    path = ~/wallpaper.jpg
    blur_passes = 3
}
 
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    outer_color = rgb(151515)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(10, 10, 10)
    placeholder_text = Contrasena
}
