monitor=,1920x1080@60,auto,1
$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun
input {
kb_layout = es
kb_model = pc105
}
general {
gaps_in = 5
gaps_out = 10
border_size = 2
layout = dwindle
}
decoration {
rounding = 10
}
animations {
enabled = yes
}
exec-once = waybar
exec-once = swaybg -i ~/wallpaper.jpg -m fill
exec-once = mako
exec-once = nm-applet
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, D, exec, $menu
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, F, fullscreen,
bind = $mainMod, L, exec, hyprlock
bind = $mainMod SHIFT, E, exec, systemctl poweroff
bind = $mainMod SHIFT, R, exec, systemctl reboot
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
